# Requisição POST para criar um novo usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name":"gustavo",
  "email":"gustavo@example.com",
  "password":"12345"
}

###

# Requisição GET para umn unico usuario
GET http://localhost:3000/users?name=gustavo&email=gustavo@example.com

### Exemplo de GET com nosql injection 
GET http://localhost:3000/users?name[$ne]=
